### ISSUE TITLE
Add plot: "latency buckets"

### ISSUE THREAD

**Issue by liamsi** [lazyledger/ipld-plugin-experiments#3]
Merge and plot the data from all nodes in a similar way as this: https://github.com/musalbas/ipfs-experiments/blob/main/dht_lookup_time/graph1.pdf

x-axis: latency
y-axis: #requests that came back in time of that bucket

This only requires to read the resulting JSON files, generated here:
https://github.com/lazyledger/ipld-plugin-experiments/blob/2e9357ef4cfa3b746c9e13932300a320ec01c76b/experiments/clients/main.go#L118-L125
The corresponding python script will have to iterate over all resulting files from each node and generate a single plot from all of them.

**Comment by evan-forbes** [comment]
Does this look about right?
![probability_bucket_example](https://user-images.githubusercontent.com/42654277/102531650-426abd00-4068-11eb-96d9-ee855d77e6ba.png)

**Comment by liamsi** [comment]
This looks great but isn't exactly what I had in mind. Left some comments below:

The title suggests that there is one of these plots per region? This might also be useful but later. Namely, if we might want to figure out if the difference in latencies is only due to different regions (as they for instance have [different ping times/download and upload speed](http://speedtest-lon1.digitalocean.com/)). But first, we want to see the total distribution over all nodes. For this, you'd need to iterate over all the resulting files (independent of their regions) and aggreagte the numbers into one plot, very similar to the one above.

The label "Probability" only makes sense if you actually normalize the total number to 1 (or 100%). It might be easier to just count the requests and label the y-axis as "Number of Requests" or sth like this. Ofc, you can transform these to probabilities if you want to (then the label is correct). But it won't change what we can derive from the plot. Feel free to skip that if it saves you some time. (In @musalbas [plot](https://github.com/musalbas/ipfs-experiments/blob/800af0b70b08406b54e2878a0e62b49b6608591a/dht_lookup_time/experiment.py#L20), he simply ran 100 requests, which is why he could count and simply label the result as "Probability").

One optional nit: I think the x-axis is hard to read. I think one could group them into 200ms buckets and only label the tick in the middle of a bar ( e.g. the bucket [0,200) would have the tick labeled as 100 ms, the second [200, 400) as 300 ms etc.).

**Comment by evan-forbes** [comment]
I see, that makes sense. Does this look better? ~~In the [report generating script](https://github.com/lazyledger/ipld-plugin-experiments/blob/evan/plotting/generate_report.py), I also generate this same plot for the DA Proof latencies, is that useful, or can it be excluded?~~ Never mind, I answered my own question...
![Screenshot from 2020-12-20 19-50-23](https://user-images.githubusercontent.com/42654277/102732243-ce4a4680-42ff-11eb-8fa1-cfa4cf94ee3e.png)

**Comment by liamsi** [comment]
Also addressed in #9 👍🏼 Closing.
