### ISSUE TITLE
Improve current plots

### ISSUE THREAD

**Issue by liamsi** [lazyledger/ipld-plugin-experiments#6]
Add description/title/legend to current plots:
![image](https://user-images.githubusercontent.com/7441766/101998784-a000b180-3cd6-11eb-9dab-cf68bb4990df.png)

At least: 
- some meaningful title
- x-axis: DA sample #
- y-axis: time in ms or sec

Nice to have:
 - meta data about the node, e.g. in the title (e.g. digital ocean region - as regions seem to show quite different behavior in terms of latency)

**Comment by evan-forbes** [comment]
Is this close to what you had in mind?
![error_bars_example](https://user-images.githubusercontent.com/42654277/102531528-0e8f9780-4068-11eb-9f3c-b7deea7b8124.png)
![region_stats](https://user-images.githubusercontent.com/42654277/102541983-c166f200-4076-11eb-9759-a6e32145e160.png)

930cf8a44154ceaba0ba59905c43d74d30d8d5ee

**Comment by liamsi** [comment]
Yeah, this is super dope! And the additional per region plot is very useful to understand the latency differences between regions.

Some questions/feedback on the first plot:

 - isn't "100 ms" easier to understand than "tenths of seconds"
 - the x-axis should be integers, where 1,2,3, ... means the first DA proof, the second  DA proof etc
 - question: did you run with 20 samples as one DA proof? 
 - "Sample Grouping" could be changed to: "DA proof (15 sample requests)" (or 20 sample requests or how many you grouped together in the experiment)
 - question: do you want to group all results of one region into a single plot? If yes, that isn't really necessary right now but also useful! It would additionally be interesting to have a plot per node (and the plot carries the info of the droplets region in its title) and one similar plot for all nodes

**Comment by evan-forbes** [comment]
I only ran 15 samples per DA proof, or whatever the default was. However, I plotted with 20 samples per groups by mistake. 

Are you looking for something similar to what is in the "errorbar_plotter.py" script for each region, or something that averages the latency for each proof across all regions? Something like this maybe? 
![Screenshot from 2020-12-20 19-50-53](https://user-images.githubusercontent.com/42654277/102733108-018dd500-4302-11eb-899b-b2eb81d29e4c.png)

**Comment by liamsi** [comment]
> Are you looking for something similar to what is in the "errorbar_plotter.py" script for each region, or something that averages the latency for each proof across all regions? Something like this maybe?

I think a plot per node/droplet, and a plot that averages over all nodes (and optionally a plot per region if much more nodes than different regions were used in an experiment) would be ideal. And yes, your plot looks perfect IMO 👌🏼

**Comment by liamsi** [comment]
I think all of this was addressed in #9. Closing this and if anything is missing will open smaller followup issues. 
Thanks @evan-forbes!
